# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  identity_url: "https://genorie.netlify.com/.netlify/identity"
  gateway_url: "https://genorie.netlify.com/.netlify/git"
  squash_merges: true
media_folder: '/images'
site_url: https://genorie.netlify.com
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
